db:
  image: bogomazov/upstartup-postgres
web:
  image: bogomazov/upstartup
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/upstartup
  ports:
    - "8000:8000"
  links:
    - db

