nginx:
   build: nginx-uwsgi/
   links:
       - django:django
   ports:
       - "80:80"
dbdata:
  image: bogomazov/upstartup-postgres
  volumes:
     - /var/lib/postgresql
  command: true
db:
    image: bogomazov/upstartup-postgres
    volumes_from:
       - dbdata
django:
    image: bogomazov/upstartup
    command: uwsgi --http :9000 --wsgi-file upstartup/wsgi.py
    # command: bash
    volumes:
         - .:/upstartup
    ports:
         - "9000:9000"
    links:
        - db

